name: kwaqua
favicon: null
layout_spectrum: 0.95729
typography_spectrum: 0.16635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a7a7a'
    - '#bcbcbc'
    - '#d8d8d8'
    - '#8f8f8f'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
