name: kwaqua
favicon: null
layout_spectrum: 0.82161
typography_spectrum: 0.16635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#004150'
    - '#988791'
    - '#009329'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
