name: kwaqua
favicon: null
layout_spectrum: 0.63439
typography_spectrum: 0.16635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060749'
    - '#040546'
    - '#a6a8bf'
    - '#9b9bb6'
    - '#141553'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
