name: kwaqua
favicon: null
layout_spectrum: 0.95729
typography_spectrum: 0.16635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2b31'
    - '#ffffff'
    - '#ababad'
    - '#1e96bc'
    - '#953c1b'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
